import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create next App</title>
        <meta name='description' content='Generated by create nex app' />
        <link rel='icon' href='/favicon.ico'/>
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org' >Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet ullam modi nulla doloribus ipsum, incidunt quia minus quisquam fu
        </p>

      </main>
    </>
  )
}

export default Home